[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/quality"
  to = "/.netlify/functions/quality"
  status = 200

[[redirects]]
  from = "/api/general-data"
  to = "/.netlify/functions/general-data"
  status = 200

[[redirects]]
  from = "/api/meetings"
  to = "/.netlify/functions/meetings"
  status = 200
