[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth-config"
  to = "/.netlify/functions/auth-config"
  status = 200

[[redirects]]
  from = "/api/quality"
  to = "/.netlify/functions/quality"
  status = 200

[[redirects]]
  from = "/api/general-data"
  to = "/.netlify/functions/general-data"
  status = 200

[[redirects]]
  from = "/api/meetings"
  to = "/.netlify/functions/meetings"
  status = 200

[[redirects]]
  from = "/api/mechanisms"
  to = "/.netlify/functions/mechanisms"
  status = 200

[[redirects]]
  from = "/api/financial-updates"
  to = "/.netlify/functions/financial-updates"
  status = 200

[[redirects]]
  from = "/api/support"
  to = "/.netlify/functions/support"
  status = 200
